### ISSUE TITLE
Is possible to import/export (sync?) with Firefox/Palemoon?

### ISSUE THREAD

**Issue by timofonic** [D630/taskwarrior-um#1]
Hello.

Thanks a lot for your Taskwarrior "extension"! ;)

I want to deploy TaskWarrior on all my systems.

REASON:

- I have extremely horrible organization habits and hopeless distraction.
  * I have been diagnosed as [Adult ADHD](https://github.com/adhdgeeks/ADHD-Geeks) two years ago.

Adding bookmarks can be interesting, because I would be able to reference these URLs in tasks if needed and use the same protocol to sync bookmarks between machines.

Are there a possibility to be able to sync bookmarks between Taskwarrior and Firefox/Palemoon?

Thanks in advance!

Kind regards.

**Comment by D630** [comment]
Hi! :)

First of all: I don't use taskum on a regular basis, because it's too slow for my taste. It's just an example, how to use UDAs in Taskwarrior. 

Taskwarrior stores its data in [JSON](http://taskwarrior.org/docs/design/task.html). For import/export you can find convertes on [this site](http://taskwarrior.org/tools/). If you just want to annotate urls with tasks, have a look at [taskopen](https://github.com/ValiValpas/taskopen).  In order to use bookmarks in taskum in combination with Firefox (or any user bookmark storage), you need to write your own converter script.
